spring.application.name=Macros

spring.datasource.url=jdbc:h2:file:./data/macrosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Spoonacular API
spoonacular.api.key=${SPOONACULAR_API_KEY}

# OpenWeatherMap API
openweathermap.api.key=${OPENWEATHERMAP_API_KEY}

# Load API keys
spring.config.import=optional:file:API_KEY[.properties]
